Include <sched.h> where needed
Many of the reproducers use setns() function but not all if them have
  #include <sched.h>
directly or via some other header.

This causes the following warnings during the build in Ubuntu 18.04
and CentOS 8:
  linux/3272058eb0f2ce2376e9cd97ea997d77f6b487e7.c: In function 'initialize_devlink_pci':
  linux/3272058eb0f2ce2376e9cd97ea997d77f6b487e7.c:257:13: warning:
    implicit declaration of function 'setns'; did you mean 'setenv'? [-Wimplicit-function-declaration]
      int ret = setns(kInitNetNsFd, 0);

Let us add "#include <sched.h>" where it is missing.

Signed-off-by: Evgenii Shatokhin <eshatokhin@virtuozzo.com>